version: '3.8'

services:
  zookeeper:
    image: 'zookeeper:3.4'
    ports:
      - '2181:2181'
    networks:
      - my_network

  kafka:
    image: 'confluentinc/cp-kafka:latest'
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "PAGAMENTO_PENDENTE:1:1,PAGAMENTO_CONFIRMADO:1:1,PRODUCAO_PENDENTE:1:1,,PRODUCAO_FINALIZADA:1:1"
    networks:
      - my_network

  app:
    image: wtof/fiapfood-pedido:latest
    ports:
      - 8081:8081
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/fiapfood_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - db
      - kafka
    networks:
      - my_network

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=fiapfood_db
    ports:
      - 3307:3306
    networks:
      - my_network

networks:
  my_network: