apiVersion: v1
kind: Service
metadata:
  name: fiapfood-pedido-service
spec:
  selector:
    app: fiapfood-pedido-api
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 30000
  type: LoadBalancer
