apiVersion: v1
kind: Service
metadata:
  name: fiapfood-pedido-service
spec:
  selector:
    app: fiapfood-api
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    #nodePort: 30000
  type: LoadBalancer
