name: Build and Deploy

on:
  push:
    branches: [ "master" ]
 
env:
  RESOURCE_GROUP: "FIAP_K8S_Terraform"
  CLUSTER_NAME: "fiapterrafromcluster"
  HPM_MANISFEST_PATH: "kubernetes/azure/infra"
  SECRETS_MANIFEST_PATH: "kubernetes/azure/secrets"
  CONFIG_MAPS_MANIFEST_PATH: "kubernetes/azure/config-maps"
  SERVICES_MANIFEST_PATH: "kubernetes/azure/services"
  DEPLOYMENT_MANIFEST_PATH: "kubernetes/azure/deployments"
  IMAGE_TAG: $(date +"%d%m%Y")
jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_CLOUD_TOKEN }}
          SONAR_HOST_URL: "https://sonarcloud.io"
        with:
          args: -Dsonar.projectKey=wtof_fiapfood-pedido -Dsonar.organization=wtof

  build:
    needs: sonarqube
    runs-on: ubuntu-latest
    steps:
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag wtof/fiapfood-pedido:${{ env.IMAGE_TAG }}
          docker build . --file Dockerfile --tag wtof/fiapfood-pedido:latest
      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker image to Docker Hub
        run: |
          docker push wtof/fiapfood-pedido:${{ env.IMAGE_TAG }}
          docker push wtof/fiapfood-pedido:latest

  deploy:
    permissions:
      actions: read
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up kubelogin for non-interactive login
        uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: 'v0.0.25'

      - name: Get K8s context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ env.RESOURCE_GROUP }}
          cluster-name: ${{ env.CLUSTER_NAME }}
          admin: 'false'
          use-kubelogin: 'true'

      - name: Deploys application
        uses: Azure/k8s-deploy@v4
        with:
          action: deploy
          manifests: |
           ${{ env.SECRETS_MANIFEST_PATH }}
           ${{ env.CONFIG_MAPS_MANIFEST_PATH }}
           ${{ env.SERVICES_MANIFEST_PATH }}
           ${{ env.DEPLOYMENT_MANIFEST_PATH }}
           ${{ env.HPM_MANISFEST_PATH }}
          images: "docker.io/wtof/fiapfood-pedido:latest"